version: '3.8'

volumes:
    datafiles:

services: 
    mysql:
        image: mysql:8.0.0
        container_name: mysql8
        environment: 
            - MYSQL_ROOT_PASSWORD=verySecretPassword
            - MYSQL_TCP_PORT=3306
        volumes:
            - datafiles:/var/lib/mysql
        restart: always

    website:
        container_name: php74
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            - MYSQL_DBHOST=mysql
            - MYSQL_DBPORT=3306
            - MYSQLDBUSER=root
            - MYSQL_DBPASS=verySecretPassword
        volumes: 
            - ./src:/var/www/html
        ports: 
            - 6080:80
        depends_on: 
            - mysql
